In [47]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("input/"))

# Any results you write to the current directory are saved as output.

#reading the training and test data
train_data = pd.read_csv('input/google-landmarks-dataset/train.csv')
test_data = pd.read_csv('input/google-landmarks-dataset/test.csv')
matching_data = pd.read_csv('input/retrieval_sample_submission.csv')

print("Training data size:",train_data.shape)
print("Test data size:",test_data.shape)
print("Retreival data size:",matching_data.shape)


['.DS_Store', 'retrieval_sample_submission.csv', 'google-landmarks-dataset']
Training data size: (1225029, 3)
Test data size: (117703, 2)
Retreival data size: (117703, 2)


In [48]:
#Downloading the images 
from IPython.display import Image
from IPython.core.display import HTML 
def display_image(url):
    img_style = "width: 500px; margin: 0px; float: left; border: 1px solid black;"
    #images_list = ''.join([f"<img style='{img_style}' src='{u}' />" for _, u in urls.head(20).iteritems()])
    image=f"<img style='{img_style}' src='{url}' />"
    display(HTML(image))

In [50]:
#Displaying the images
for x in range(100):
    display_image(train_data['url'][x])

In [51]:
from keras.preprocessing import image
def path_to_tensor(img_path):
    # loads RGB image as PIL.Image.Image type
    img = image.load_img(img_path, target_size=(224, 224))
    # convert PIL.Image.Image type to 3D tensor with shape (224, 224, 3)
    x = image.img_to_array(img)
    # convert 3D tensor to 4D tensor with shape (1, 224, 224, 3) and return 4D tensor
    return np.expand_dims(x, axis=0)

In [52]:
import sys
# https://gist.github.com/vladignatyev/06860ec2040cb497f0f3
# vladignatyev's progress bar
# remove later
def progress(count, total, status=''):
    bar_len = 60
    filled_len = int(round(bar_len * count / float(total)))

    percents = round(100.0 * count / float(total), 1)
    bar = '=' * filled_len + '-' * (bar_len - filled_len)

    sys.stdout.write('[%s] %s%s ...%s\r' % (bar, percents, '%', status))
    sys.stdout.flush()  # As suggested by Rom Ruben (see: http://stackoverflow.com/questions/3173320/text-progress-bar-in-the-console/27871113#comment50529068_27871113)


In [53]:
def setter(x, adder, data):
    try:
        url1 = data['url'][x+adder]
        urllib.request.urlretrieve(url1, 'tempfiles/evaluated.jpg')
        return True
    except:
        return False

In [54]:
from tensorflow.python.keras.applications import ResNet50
from tensorflow.python.keras.models import Sequential
import urllib.request
import scipy
import pandas as pd

def create_resnet50_csv(data, length, suffix):

    url0 = data['url'][0]
    urllib.request.urlretrieve(url0, 'tempfiles/evaluated.jpg')

    model = Sequential()
    model = ResNet50(include_top=False, weights='imagenet')


    evaluated_coords = model.predict(path_to_tensor("tempfiles/evaluated.jpg"))

    flat = evaluated_coords.flatten()

    datalist = [flat]

    index_list = np.full((1,1), 0)

    adder = 1

    for x in range(length-1):
        progress(x,length-1)
        temp = setter(x, adder, data)
        while temp is not True:
            adder += 1
            temp = setter(x, adder, data)
        evaluated_coords = model.predict(path_to_tensor("tempfiles/evaluated.jpg"))
        flat = evaluated_coords.flatten()
        datalist = np.append(datalist, [flat], axis=0)

        current_row = np.full((1,1), x+adder)
        index_list = np.append(index_list, current_row)


    dataframe = pd.DataFrame(datalist)
    index_dataframe = pd.DataFrame(index_list)
    
    dataframe.to_csv("data/bottleneck_features" + suffix + ".csv", sep=',', encoding='utf-8')
    index_dataframe.to_csv("data/indices" + suffix + ".csv", sep=',', encoding='utf-8')

create_resnet50_csv(train_data, 100, "_train")
create_resnet50_csv(test_data, 100, "_test")

/anaconda3/lib/python3.7/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


/anaconda3/lib/python3.7/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


In [89]:
def is_same_landmark(indices, id_getter, row1, row2):
    actual_row1 = indices.iloc[row1][1]
    actual_row2 = indices.iloc[row2][1]
    id1 = id_getter['landmark_id'][actual_row1]
    id2 = id_getter['landmark_id'][actual_row2]
    return id1 == id2

In [85]:
indices = pd.read_csv('data/indices_train.csv')
print(is_same_landmark(indices,train_data,89,84))

6051
True


In [105]:
import random

def to_add():
    if random.random()<0.0043:
        return True
    else:
        return False

In [110]:
def add_row(data_array, bottleneck_features, indices, row_num):
    row = bottleneck_features.iloc[row_num]
    for x in range(100):
        combined_row = []
        if x != row_num:
            eval_row = bottleneck_features.iloc[x]
            if is_same_landmark(indices, train_data, row_num, x):
                combined_row = np.append([1], row)
                combined_row = np.append(combined_row, eval_row)
            else:
                if (to_add()):
                    combined_row = np.append([0], row)
                    combined_row = np.append(combined_row, eval_row)
                    
        if len(combined_row) > 0:
            if data_array is None:
                data_array = [combined_row]
            else:
                data_array = np.append(data_array, [combined_row], axis=0)
    return data_array

In [111]:
bottleneck_features = pd.read_csv('data/bottleneck_features_train.csv')
def make_dataset(bottleneck_features, indices):
    data_array = None
    for x in range(100):
        progress(x,100)
        data_array = add_row(data_array, bottleneck_features, indices, x)
        print(data_array)
    dataframe = pd.DataFrame(data_array)
    dataframe.to_csv("data/paired_data.csv", sep=',', encoding='utf-8')

make_dataset(bottleneck_features, indices)

[array([ 0.      ,  0.      , -0.      , ...,  3.760726, -0.      , ...
       -0.      ])]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]]
[[ 0.          0.         -0

[[ 0.0000000e+00  0.0000000e+00 -0.0000000e+00 ...  3.7607260e+00.0% ...
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ...  4.2114880e-01
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00  3.5979896e+00]
 ...
 [ 1.0000000e+00  2.0000000e+01 -0.0000000e+00 ...  7.7641835e+00
  -0.0000000e+00 -0.0000000e+00]
 [ 1.0000000e+00  2.0000000e+01 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00 -0.0000000e+00]
 [ 1.0000000e+00  2.0000000e+01 -0.0000000e+00 ...  4.6671630e-03
  -0.0000000e+00  4.9407410e+00]]
[[ 0.0000000e+00  0.0000000e+00 -0.0000000e+00 ...  3.7607260e+00.0% ...
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ...  4.2114880e-01
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00  3.5979896e+00]
 ...
 [ 1.0000000e+00  2.0000000e+01 -0.0000000e+00 ...  7.7641835e+00
  -0.0000000e+00 -

[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]
 ...
 [ 0.        32.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        34.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        35.        -0.        ... -0.        -0.        -0.       ]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]
 ...
 [ 0.        32.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        34.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        35.        -0.        ... -0.        -0.        -0.       ]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ... 

[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]
 ...
 [ 0.        52.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        52.        -0.        ...  5.647515  -0.         0.851339 ]
 [ 0.        53.        -0.        ... -0.        -0.        -0.       ]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]
 ...
 [ 0.        52.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        52.        -0.        ...  5.647515  -0.         0.851339 ]
 [ 0.        53.        -0.        ... -0.        -0.        -0.       ]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ... 

[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]
 ...
 [ 0.        71.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        71.        -0.        ...  4.0785413 -0.        -0.       ]
 [ 1.        73.        -0.        ...  2.3850055 -0.        -0.       ]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ...  0.4211488 -0.        -0.       ]
 [ 0.         1.        -0.        ... -0.        -0.         3.5979896]
 ...
 [ 0.        71.        -0.        ... -0.        -0.        -0.       ]
 [ 0.        71.        -0.        ...  4.0785413 -0.        -0.       ]
 [ 1.        73.        -0.        ...  2.3850055 -0.        -0.       ]]
[[ 0.         0.        -0.        ...  3.760726  -0.        -0.       ]
 [ 0.         1.        -0.        ... 

[[ 0.0000000e+00  0.0000000e+00 -0.0000000e+00 ...  3.7607260e+00.0% ...
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ...  4.2114880e-01
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00  3.5979896e+00]
 ...
 [ 1.0000000e+00  8.4000000e+01 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00  1.6311076e-02]
 [ 1.0000000e+00  8.4000000e+01 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00 -0.0000000e+00]
 [ 1.0000000e+00  8.4000000e+01 -0.0000000e+00 ...  4.6671630e-03
  -0.0000000e+00  4.9407410e+00]]
[[ 0.0000000e+00  0.0000000e+00 -0.0000000e+00 ...  3.7607260e+00.0% ...
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ...  4.2114880e-01
  -0.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00  3.5979896e+00]
 ...
 [ 1.0000000e+00  8.9000000e+01 -0.0000000e+00 ... -0.0000000e+00
  -0.0000000e+00  